import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const CONFIG = {
  username: "baotoq",
  excludeForks: true,
  excludeArchived: true,
  minStars: 0,
  maxRepos: 6,
  excludeRepos: ["baotoq"], // GitHub profile repo
};

interface GitHubApiRepo {
  name: string;
  html_url: string;
  description: string | null;
  language: string | null;
  stargazers_count: number;
  forks_count: number;
  pushed_at: string;
  fork: boolean;
  archived: boolean;
  topics: string[];
}

interface GitHubRepo {
  name: string;
  url: string;
  description: string;
  language: string | null;
  stars: number;
  forks: number;
  updatedAt: string;
}

async function fetchRepos(): Promise<GitHubApiRepo[]> {
  const url = `https://api.github.com/users/${CONFIG.username}/repos?sort=pushed&direction=desc&per_page=100&type=owner`;

  const headers: Record<string, string> = {
    Accept: "application/vnd.github.v3+json",
  };

  const token = process.env.GITHUB_TOKEN;
  if (token) {
    headers.Authorization = `Bearer ${token}`;
  }

  const response = await fetch(url, { headers });

  if (!response.ok) {
    throw new Error(`GitHub API responded with ${response.status}: ${response.statusText}`);
  }

  return response.json() as Promise<GitHubApiRepo[]>;
}

function filterRepos(repos: GitHubApiRepo[]): GitHubApiRepo[] {
  return repos
    .filter((repo) => {
      if (CONFIG.excludeForks && repo.fork) return false;
      if (CONFIG.excludeArchived && repo.archived) return false;
      if (repo.stargazers_count < CONFIG.minStars) return false;
      if (CONFIG.excludeRepos.includes(repo.name)) return false;
      return true;
    })
    .slice(0, CONFIG.maxRepos);
}

function transformRepo(repo: GitHubApiRepo): GitHubRepo {
  return {
    name: repo.name,
    url: repo.html_url,
    description: repo.description ?? "No description",
    language: repo.language,
    stars: repo.stargazers_count,
    forks: repo.forks_count,
    updatedAt: repo.pushed_at,
  };
}

function writeDataFile(repos: GitHubRepo[]): void {
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  const outputPath = join(scriptDir, "..", "src", "data", "github.ts");

  const content = `import type { GitHubRepo } from "@/types/resume";

// Auto-generated by scripts/fetch-github.ts on ${new Date().toISOString()}
// Do not edit manually — changes will be overwritten on next build
export const githubRepos: GitHubRepo[] = ${JSON.stringify(repos, null, 2)};
`;

  writeFileSync(outputPath, content, "utf-8");
}

async function main(): Promise<void> {
  try {
    const rawRepos = await fetchRepos();
    const filtered = filterRepos(rawRepos);
    const transformed = filtered.map(transformRepo);

    writeDataFile(transformed);
    console.log(`Wrote ${transformed.length} repos to src/data/github.ts`);
  } catch (error) {
    console.warn("GitHub API unavailable, using existing fallback data");
    console.warn(error instanceof Error ? error.message : String(error));
    process.exit(0);
  }
}

main();
