import type { GitHubRepo } from "@/types/resume";

// Auto-generated by scripts/fetch-github.ts on 2026-03-06T07:17:41.234Z
// Do not edit manually — changes will be overwritten on next build
export const githubRepos: GitHubRepo[] = [
  {
    "name": "resume",
    "url": "https://github.com/baotoq/resume",
    "description": "No description",
    "language": "TypeScript",
    "stars": 0,
    "forks": 0,
    "updatedAt": "2026-03-06T06:58:38Z"
  },
  {
    "name": "shitcoin",
    "url": "https://github.com/baotoq/shitcoin",
    "description": "No description",
    "language": "Go",
    "stars": 0,
    "forks": 0,
    "updatedAt": "2026-03-05T14:34:49Z"
  },
  {
    "name": "trading-bot",
    "url": "https://github.com/baotoq/trading-bot",
    "description": "No description",
    "language": "C#",
    "stars": 0,
    "forks": 0,
    "updatedAt": "2026-03-04T13:49:21Z"
  },
  {
    "name": "micro-commerce",
    "url": "https://github.com/baotoq/micro-commerce",
    "description": ".NET 10 .NET Aspire",
    "language": "C#",
    "stars": 93,
    "forks": 25,
    "updatedAt": "2026-03-02T17:37:17Z"
  },
  {
    "name": "simple-dex",
    "url": "https://github.com/baotoq/simple-dex",
    "description": "No description",
    "language": "Solidity",
    "stars": 0,
    "forks": 0,
    "updatedAt": "2026-02-26T10:05:24Z"
  },
  {
    "name": "go-shortener",
    "url": "https://github.com/baotoq/go-shortener",
    "description": "No description",
    "language": "Go",
    "stars": 0,
    "forks": 0,
    "updatedAt": "2026-02-22T10:16:23Z"
  }
];
