import type { GitHubRepo } from "@/types/resume";

// This file is auto-generated by scripts/fetch-github.ts
// Manual edits will be overwritten on next build
// Fallback: if the prebuild script fails, this checked-in version is used
export const githubRepos: GitHubRepo[] = [];
